services:
  app:
    build: .
    ports:
      - 3005:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - uploads_data:/app/uploads
      - converted_data:/app/converted
    networks:
      - proxy

volumes:
  uploads_data:
  converted_data:

networks:
  proxy:
    external: true